import { NgModule } from '@angular/core';
/* import { MatMomentDateModule } from '@angular/material-moment-adapter'; */
import {
  MatButtonModule,
  MatTabsModule,
  MatInputModule,
  MatMenuModule,
  MatIconModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatFormFieldModule,
  MatToolbarModule,
  MatSelectModule,
  MatSidenavModule,
  MatRadioModule,
  MatCardModule,
  MatTableModule,
  MAT_DATE_LOCALE,
  MatExpansionModule,
  MatProgressSpinnerModule
} from '@angular/material';
@NgModule({
  declarations: [],
  imports: [MatButtonModule,
    MatTabsModule,
    MatInputModule,
    MatMenuModule,
    MatIconModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatToolbarModule,
    MatSelectModule,
    MatSidenavModule,
    MatRadioModule,
    MatCardModule,
    MatButtonModule,
    MatExpansionModule,
    MatTableModule,
    MatProgressSpinnerModule
  ],
  exports: [MatButtonModule,
    MatTabsModule,
    MatInputModule,
    MatMenuModule,
    MatIconModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatToolbarModule,
    MatSelectModule,
    MatSidenavModule,
    MatRadioModule,
    MatCardModule,
    MatButtonModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatExpansionModule]
})
export class MaterialModule { }
